### ISSUE TITLE
Can't run with pythonw

### ISSUE THREAD

**Issue by mkierc** [davidramiro/fluxee#1]
I was trying to get the `fluxee.py` to run in the background without the console window. The default method for that would be to use `pythonw` interpreter instead of `python`.

Unfortunately running `pythonw fluxee.py` or even changing the extenstion to `fluxee.pyw` causes the script to immediately terminate.

After a bit of research I found out a few things:

1. Python in no-console mode does not like errors/exceptions/any output - so I've tried to simply comment all the print statements - no luck there
2. Bottle has a *quiet mode*, that prevents it from producing any output - but it still does not mitigate the issue
3. The program is still somehow triggering the immediate termination, but I didn't dig deep enough into the code to determine what is the cause

I can't simply use the prebuilt `.exe` version, because I wanted to change some things in the code (for example I wanted the brightness to be constant all the time at 50%, not at 100% at startup because it melts my eyes ;)). For now I just use a dirty trick of using:
```
cmd /k "C:\Programy\Python364\pythonw.exe P:\yeelight-fluxee-master\fluxee.py 1>stdout.txt 2>stderr.txt"
exit
```
But it's really annoying.

**Comment by davidramiro** [comment]
Since I just got started with Python in general I can't really tell why pythonw is not working. But generally, this is a good idea to implement, the console is not needed once everything is set up and running. I will try to read up on that and see if I can get it to run, while a batch file with your "dirty" workaround would do the trick right now.

As for the brightness, I just worked with 100% starting brightness as it's fitting for my light setup and f.lux sends back its own brightness settings starting at 100. I could either implement a own custom static brightness via console or add a brightness multiplier to the config so that it would still be dynamic but start at a lower value. What do you think?

**Comment by davidramiro** [comment]
After a second glance over this issue: running bottle.py, a substancial part of this script, is simply not possible with pythonw. Hence this is not possible, sadly.

See https://github.com/bottlepy/bottle/issues/1104
